version: '3.8'

volumes:
  mysql-volume:
  # session_redis_data:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: match_php-fpm
    volumes:
      - ./src/:/var/www/html
    environment:
      - DB_CONNECTION=match
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: match_web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: match_database
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
  node:
    build: ./docker/node
    container_name: match_node
    volumes:
      - ./src/:/app
    working_dir: /app/frontend
  # session_redis:
  #   image: redis:5.0.6-alpine
  #   container_name: session_redis
  #   command: redis-server --appendonly yes
  #   ports: 
  #     - 6379:6379
  #   volumes:
  #     - session_redis_data:/data
